### AVAILABLE LANGUAGES - English, Spanish, Italian, Russian, Vietnamese, Simplified Chinese.
Language: English

Debugging: false #Shows additional messages and information related to the plugin in the console. Enabling it may cause lag.

Autosave Interval: 120 #In seconds, it is recommended to keep this number above 60 in order to avoid possible lag spikes.

###DATABASE CONFIGURATION###
#Coming soon

#--------------------KARMA ALIGNMENTS SETTINGS---------------------#

Alignment Thresholds: #Karma Score alignment thresholds, AKA the current alignment based on the amount of Karma a player has.
#- The alignments' names can be changed in the language files.
#- Always write the lower number first and the higher number second.
#- The lower threshold (First number) of the EVIL alignment and the higher threshold (second number) of the BEST alignment will work as a limit for
#  the amount of Karma points obtainable.
  EVIL: [-2147483647, -50000]
  VILE: [-49999, -30000] #E.G. This alignment is obtained when a player's karma is between the first number and the second number.
  MEAN: [-29999, -15000]
  RUDE: [-14999, -5000]

  NEUTRAL: [-4999, 9999]

  KIND: [10000, 24999]
  GOOD: [25000, 49999]
  PURE: [50000, 99999]
  BEST: [100000, 2147483647]  #2147483647 is the highest/lowest integer usable.

#Set to true if you want alignments to show next to a player's name, or false if you want the player's name color to change based on their alignment.
Show Alignments: true

#Where alignments should be visible.

Tablist Alignment: true #Works only if there is no 'tablist' plugin in the server. If such plugin is enabled, use the PAPI %karma_alignment%/%karma_aligned_name% placeholder instead
Chat Alignment: true
Display Name Alignment: false #Currently not implemented.

#------------------------KARMA SETTINGS--------------------------#

#Karma changed by being online in the server. In order to change this, a player will have to quit and join the server.
Passive Karma Gain:
  Enabled: true
  Amount: 1.0
  Interval: 300 #In seconds

#Karma changed by killing passive entities in the server.
Passive Mob Killing:
  Enabled: true
  Amount: -1.0

#Karma changed by killing monsters in the server.
Monster Killing:
  Enabled: true
  Amount: 1.0

#Karma changed by killing friendly entities in the server.
Friendly Mob Killing:
  Enabled: true
  Amount: -10.0

#Karma changed by killing players in the server. The amount of Karma gained/lost can be changed depending on the killed player's alignment.
Player Killing:
  Enabled: false
  Alignment Amount:
    EVIL: 50.0
    VILE: 25.0
    MEAN: 15.0
    RUDE: 5.0

    NEUTRAL: 0.0

    KIND: -15.0
    GOOD: -50.0
    PURE: -100.0
    BEST: -250.0

#Karma changed by hitting players in the server. The amount of Karma gained/lost can be changed depending on the hit player's alignment.
Player Hitting:
  Enabled: false
  Alignment Amount:
    EVIL: 2.0
    VILE: 1.5
    MEAN: 1.0
    RUDE: 0.5

    NEUTRAL: 0.0

    KIND: -2.0
    GOOD: -3.0
    PURE: -4.0
    BEST: -5.0

#Karma changed by trading with villagers
Villager Trading:
  Enabled: true
  Amount: 2.0

#Karma changed by hitting a villager
Villager Hitting:
  Enabled: true
  Amount: -5.0

#Karma changed when entity is tamed
Entity Tamed:
  Enabled: true
  Amount: 10.0

#Karma changed when entity is fed
Entity Fed:
  Enabled: true
  Amount: 1.0

#Karma changed when server is voted. Not implemented
Server Voted:
  Enabled: true
  Amount: 50.0

#Karma changed when golden carrot is consumed
Golden Carrot Consumed:
  Enabled: true
  Amount: 5.0

#Karma changed by placing blocks. Any block found here may be added, followed by the amount of karma to be added-removed: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
Placing Blocks:
  Enabled: false
  Blocks:
    TNT: -1.0
    LAVA: -1.0

#Karma changed by breaking blocks. Any block found here may be added, followed by the amount of karma to be added-removed.
#List of blocks available for 1.13+: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#List of blocks available for 1.8-1.12.2: https://helpch.at/docs/1.12.2/index.html?org/bukkit/Material.html
Breaking Blocks:
  Enabled: false
  Blocks:
    TNT: 1.0

#Karma changed by sending messages containing certain words (Not case sensitive).
Message Sent:
  Enabled: true
  Words:
    blackspigot: -1.0
    dumb: -5.0
    thank you: 1.0

#Maximum amount of karma which can be obtained every x seconds.
Karma Limit:
  Max Amount: 150.0
  Interval: 3600

#Multiplier to apply to the amount of Karma GAINED if it is of the same source as the previous time Karma was gained.
Decrease Multiplier:
  Enabled: true
  Amount: 0.5 #<-- (Instead of gaining 10.0 points, a player will gain 5.0)

#Multiplier to apply to the amount of karma LOST if it is of the same source as the previous time Karma was lost.
Increase Multiplier:
  Enabled: true
  Amount: 2.5 #<-- (Instead of gaining 10 points, a player will gain 25.0)

#--------------------KARMA PERKS - REPERCUSSIONS---------------------#

#The written numbers will indicate the chance/amount for each respective parameter.
#Each parameter will accept 4 values, each for each positive/negative alignment.

#-----PERKS-----#
#Written values are for the following alignments, in the written order: Kind, Good, Pure, Best.

Effects:
  Positive:   #Perks that being of a good alignment are given to players.
      #Whether players should have the possibility of gaining extra enchantments upon enchanting.
    Enchanting: [20, 30, 40, 50]   #Base % chance of the extra enchantment being added.
      #Whether players should gain extra experience upon picking some up.
    Experience: [1.25, 1.50, 1.75, 2.0]  #Multiplier assigned to the amount of experience gained.
      #Whether mobs killed by well-aligned players should have a possibility to drop extra loot.
    Drops: [20, 40, 60, 80]   #Base % chance of extra loot being generated.
      #Whether players should have a possibility of non-smeltable ores to re-generate upon being mined.
    Mining: [5, 10, 15, 20]   #Base % chance of the ore re-generating, 1.5 seconds after being broken.
      #Whether players should have a multiplier applied to the Karma they gain.
    Karma Gained: [1.00, 1.00, 1.00, 1.00]  #Multiplier assigned to the amount of Karma gained.
      #Whether player should have a multiplier applied to the Karma they lose.
    Karma Lost: [2.00, 2.25, 2.50, 2.75]   #Multiplier assigned to the amount of Karma lost.

#--REPERCUSSIONS--#
#Written values are for the following alignments, in the written order: Rude, Mean, Vile, Evil.

  Negative:   #Repercussions that being of a bad alignment has on the players.
      #Whether players should have the possibility of losing one enchantment upon enchanting. Additionally, enchanted items can gain curses.
    Enchanting: [50, 60, 70, 80]   #Base % chance of an enchantment being removed. Half of the value will be the chance of cursing the enchanted item.
      #Whether players should gain less experience upon picking some up.
    Experience: [0.75, 0.65, 0.55, 0.45]  #Multiplier assigned to the amount of experience gained.
      #Whether mobs killed by players should have the possibility to drop no loot/no experience.
    Drops: [20, 30, 40, 50]   #Base % chance of no loot being generated.
      #Whether players should have the possibility of any ore to drop cobblestone instead of its respective mineral upon being mined.
    Mining: [20, 30, 40, 50]   #Base % chance of the ore dropping cobblestone.
      #Whether players should have a multiplier applied to the Karma they gain.
    Karma Gained: [2.00, 2.25, 2.50, 2.75]   #Multiplier assigned to the amount of Karma gained.
      #Whether player should have a multiplier applied to the Karma they lose.
    Karma Lost: [1.00, 1.00, 1.00, 1.00]   #Multiplier assigned to the amount of Karma lost.
      #Whether players should have the chance of being struck by a lightning during a thunderstorm, if they are outside.
    Lightning: [8, 12, 16, 20]   #Base % chance for a player to be struck by a lightning, shortly after another lightning strikes a location far from the player.
      #Whether a player should have a multiplier applied to the money they earn. REQUIRES VAULT TO FUNCTION!!!
    Mobs Anger:
      Bee: [2.75, 3.00, 3.25, 3.50] #Base % chance of a bee near a player to become aggressive every second.
      Wolf: [1.25, 1.50, 1.75, 2.00] #Base % chance of a wolf near a player to become aggressive every second.
      Pigman: [0.25, 0.50, 0.75, 1.00] #Base % chance of a pig-man zombie near a player to become aggressive every second.

#--------------------MISCELLANEOUS-------------------#

#Whether Karma can be gained in creative/spectator mode or not.
Creative Mode Karma: false

#Worlds in which Karma cannot be gained.
Disabled Worlds:
  #- worldTest
  #- world1

#Any commands that should be ran by the console once the player reaches an alignment.
#This can be used to add/remove permissions from a player once they reach an alignment, if the server is using a permissions plugin.
#<PLAYER> will be replaced with the involved player's name.
Alignment Commands:
  EVIL:
    - "say I am EVIL"
    - "say <PLAYER> !!!"
  VILE:
    - "say I am VILE"
    - "say <PLAYER> !!!"
  MEAN:
    - "say I am MEAN"
    - "say <PLAYER> !!!"
  RUDE:
    - "say I am RUDE"
    - "say <PLAYER> !!!"
  NEUTRAL:
    - "say I am INEVITABLE"
    - "say <PLAYER> !!!"
  KIND:
    - "say I am KIND"
    - "say <PLAYER> !!!"
  GOOD:
    - "say I am GOOD"
    - "say <PLAYER> !!!"
  PURE:
    - "say I am PURE"
    - "say <PLAYER> !!!"
  BEST:
    - "say I am the BEST"
    - "say <PLAYER> !!!"